import { NextResponse } from 'next/server'
import type { TailorResult } from '@/app/dashboard/tailor/page'

export interface ExportRequest {
  companyName: string
  jobTitle: string
  tailoredResult: TailorResult
}

function generateResumeTxt(data: ExportRequest): string {
  const { companyName, jobTitle, tailoredResult } = data

  const lines: string[] = [
    '═'.repeat(80),
    `TAILORED RESUME FOR ${companyName} - ${jobTitle}`.toUpperCase(),
    '═'.repeat(80),
    '',
    '📊 ATS SCORE: ' + tailoredResult.analysis.ats_score,
    tailoredResult.analysis.score_explanation,
    '',
    '─'.repeat(80),
    'KEY MATCHES',
    '─'.repeat(80),
  ]

  tailoredResult.key_matches?.forEach((match) => {
    lines.push(`✓ ${match}`)
  })

  if (tailoredResult.key_gaps && tailoredResult.key_gaps.length > 0) {
    lines.push('')
    lines.push('─'.repeat(80))
    lines.push('GAPS TO ADDRESS')
    lines.push('─'.repeat(80))
    tailoredResult.key_gaps.forEach((gap) => {
      lines.push(`✗ ${gap}`)
    })
  }

  lines.push('')
  lines.push('═'.repeat(80))
  lines.push('PROFESSIONAL SUMMARY')
  lines.push('═'.repeat(80))
  lines.push('')

  // Find summary section
  const summarySection = tailoredResult.tailored_sections?.find(
    (s) => s.section_type === 'summary'
  ) as any

  if (summarySection) {
    lines.push('BEFORE:')
    lines.push(summarySection.original || '(No original summary)')
    lines.push('')
    lines.push('AFTER:')
    lines.push(summarySection.tailored || '')
  }

  lines.push('')
  lines.push('═'.repeat(80))
  lines.push('EXPERIENCE (TAILORED)')
  lines.push('═'.repeat(80))
  lines.push('')

  // Experience sections
  const experienceSections = tailoredResult.tailored_sections?.filter(
    (s) => s.section_type === 'experience'
  ) as any[]

  experienceSections?.forEach((exp, idx) => {
    lines.push(`${exp.company} — ${exp.role}`)
    if (exp.dates) lines.push(`${exp.dates}`)
    lines.push('')

    if (exp.tailored_bullets && exp.tailored_bullets.length > 0) {
      exp.tailored_bullets.forEach((bullet: string) => {
        lines.push(`• ${bullet}`)
      })
    }

    if (idx < experienceSections.length - 1) {
      lines.push('')
    }
  })

  lines.push('')
  lines.push('═'.repeat(80))
  lines.push('COVER LETTER')
  lines.push('═'.repeat(80))
  lines.push('')
  lines.push(tailoredResult.cover_letter || '(No cover letter generated)')

  lines.push('')
  lines.push('═'.repeat(80))
  lines.push('HOW TO USE THIS EXPORT')
  lines.push('═'.repeat(80))
  lines.push('')
  lines.push('1. Copy the sections you want to update')
  lines.push('2. Open your master resume in Word or Google Docs')
  lines.push('3. Update your summary and experience bullets')
  lines.push('4. Copy the cover letter into a separate document')
  lines.push('')
  lines.push('Generated by Applimatic')
  lines.push(`Date: ${new Date().toLocaleDateString()}`)

  return lines.join('\n')
}

export async function POST(request: Request) {
  try {
    const body = await request.json() as ExportRequest
    const { companyName, jobTitle } = body

    // Generate text content
    const textContent = generateResumeTxt(body)

    // Return as downloadable file
    const filename = `${companyName
      .replace(/\s+/g, '_')
      .toLowerCase()}_${jobTitle
      .replace(/\s+/g, '_')
      .toLowerCase()}_resume.txt`

    return new Response(textContent, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    })
  } catch (error) {
    console.error('Export resume error:', error)
    return NextResponse.json(
      {
        status: 'error',
        message: 'Failed to export resume',
        error: error instanceof Error ? error.message : String(error),
      },
      { status: 500 }
    )
  }
}
